openapi: 3.0.1
info:
  title: Starknet
  description: ''
  version: 1.0.0
tags:
  - name: version
#  - name: v0_7
paths:
  /{specVersion}:
    post:
      tags:
        - version
#  /v0_7:
#    post:
#      tags:
#        - v0_7
#  /v0_8:
#    post:
#      tags:
#        - v0_8